# 선형방정식
* 하나의 1차방정식 : 초등, 중학교 수학교과서를 참조하여 스스로 푼다.
* 연립방정식 : 가우스 소거법(Gaussian elimination)
* LU decomposition: numpy.linalg.solve

* Solve  
$\begin{eqnarray}
w+3x-4y+2z=0 \\
4x-2y+z=6 \\
2w-x+3y-z=5 \\
w+x+y+z=10
\end{eqnarray}$

* 위의 연립방정식은 다음처럼 행렬로 표시할 수 있다.  
$\begin{align}
\begin{pmatrix}
1 & 3 & -5 & 2 \\
0 & 4 & -2 & 1 \\
2 & -1 & 3 & -1 \\
1 & 1 & 1 & 1 
\end{pmatrix}
\begin{pmatrix}
w \\ x \\ y \\ z 
\end{pmatrix}
=
\begin{pmatrix}
0 \\ 6 \\ 5 \\ 10 
\end{pmatrix}
\end{align}$  
간단히 다음처럼 쓰기로 하자.  
$\begin{align}
A x = b
\end{align}$  
여기에서 $A$는 행렬, $x$, $b$는 벡터이다.
이 식에서 $x$를 구하면 위의 연립방정식을 푸는 것과 동일하다. 이 식의 해는 $A$의 역행렬을 이용하면 형식적으로 표기할 수 있다.  
$\begin{align}
x = A^{-1} b
\end{align}$  

In [10]:
import numpy as np
A=np.array([[1,3,-5,2],[0,4,-2,1],[2,-1,3,-1],[1,1,1,1]])
b=np.array([0,6,5,10])
x=np.dot(np.linalg.inv(A),b)
x

array([1., 2., 3., 4.])

### LU decomposition
#### 만약 x를 구하는 것이 목적이라면 역행렬을 구하는 대신 가우스 소거법 혹은 LU decomposition을 쓰는 것이 좋다.
4 $\times$ 4 행렬 $A$가 있다.  
A=$\begin{align}
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44} 
\end{pmatrix}
\end{align}$  
이 행렬은 다음의 방정식을 만족한다.  
$\begin{equation} Ax=b \end{equation}$  

$A$를 두개의 삼각행렬의 곱($LU$)으로 나누어 쓸 수 있다고 하자. $L$은 lower matrix, $U$는 upper matrix라고 부르자. 이 행렬은 다음의 방정식을 만족한다.  
$\begin{equation} Ax=LUx = b \end{equation}$   

$\begin{align}
\begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44} 
\end{pmatrix}
=
\begin{pmatrix}
l_{11} & 0 & 0 & 0 \\
l_{21} & l_{22} & 0 & 0 \\
l_{31} & l_{32} & l_{33} & 0 \\
l_{41} & l_{42} & l_{43} & l_{44} 
\end{pmatrix}
\begin{pmatrix}
u_{11} & u_{12} & u_{13} & u_{14} \\
0 & u_{22} & u_{23} & u_{24} \\
0 & 0 & u_{33} & u_{34} \\
0 & 0 & 0 & u_{44} 
\end{pmatrix}
\end{align}$  

그러면 이제 $Ax=b$를 푸는 대신 아래의 두 개의 삼각행렬로 이루어진 행렬방정식을 풀면 된다.  
$\begin{equation} 
Ux=y, \\
Ly=b
\end{equation}$   

삼각행렬의 행렬방정식을 푸는 것은 아래처럼 매우 간단하다.  
$\begin{align}
\begin{pmatrix}
t_{11} & t_{12} & t_{13} & t_{14} \\
0 & t_{22} & t_{23} & t_{24} \\
0 & 0 & t_{33} & t_{34} \\
0 & 0 & 0 & t_{44} 
\end{pmatrix}
\begin{pmatrix}
w \\ x \\ y \\ z 
\end{pmatrix}
=
\begin{pmatrix}
v_1 \\ v_2 \\ v_3 \\ v_4 
\end{pmatrix}
\end{align}$  
그러면 $x$는 간단히 계산할 수 있다.  
$\begin{align}
v_4&=t_{44}z \\
v_3&=t_{33}y+t_{34}z=t_{33}y+t_{34} \frac{v_4}{t_{44}} , \\
\cdots
\end{align}$  


나머지 문제는 $L$과 $U$를 구하는 방법이다. 이를 위해 다음처럼 $L$과 $U$를 다시 분해하자.  
$L=L_1 L_2 L_3 L_4$, $U=L_4^{-1} L_3^{-1} L_2^{-1} L_1^{-1} A$.  

따라서
$\begin{align}
LU x = L_1 L_2 L_3 L_4 L_4^{-1} L_3^{-1} L_2^{-1} L_1^{-1} A x = b
\end{align}$

그러면 다음처럼 $L_i$를 적으면 된다.  
$\begin{align}  
L_1= 
\begin{pmatrix}
a_{11} & 0 & 0 & 0 \\
a_{21} & 1 & 0 & 0 \\
a_{31} & 0 & 1 & 0 \\
a_{41} & 0 & 0 & 1 
\end{pmatrix},  \quad
L_2= 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & b_{22} & 0 & 0 \\
0 & b_{32} & 1 & 0 \\
0 & b_{42} & 0 & 1 
\end{pmatrix}, \quad
L_3= 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & c_{33} & 0 \\
0 & 0 & c_{43} & 1 
\end{pmatrix}, \quad
L_4= 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & d_{44} 
\end{pmatrix}.
\end{align}$  
그러면  
$\begin{align}  
L=L_1 L_2 L_3 L_4= 
\begin{pmatrix}
a_{11} & 0 & 0 & 0 \\
a_{21} & b_{22} & 0 & 0 \\
a_{31} & b_{32} & c_{33} & 0 \\
a_{41} & b_{42} & c_{43} & d_{44} 
\end{pmatrix}, 
\end{align}$  
역행렬도 쉽게 구할 수 있다.  
$\begin{align}  
L_1^{-1}=\frac{1}{a_{11}} 
\begin{pmatrix}
1 & 0 & 0 & 0 \\
-a_{21} & a_{11} & 0 & 0 \\
-a_{31} & 0 & a_{11} & 0 \\
-a_{41} & 0 & 0 & a_{11} 
\end{pmatrix},  \quad
L_2^{-1}= \frac{1}{b_{22}}
\begin{pmatrix}
b_{22} & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & -b_{32} & b_{22} & 0 \\
0 & -b_{42} & 0 & b_{22} 
\end{pmatrix}, \quad
L_3^{-1}=\frac{1}{c_{33}} 
\begin{pmatrix}
c_{33} & 0 & 0 & 0 \\
0 & c_{33} & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & -c_{43} & c_{33} 
\end{pmatrix}, \quad
L_4^{-1}=\frac{1}{d_{44}} 
\begin{pmatrix}
d_{44} & 0 & 0 & 0 \\
0 & d_{44} & 0 & 0 \\
0 & 0 & d_{44} & 0 \\
0 & 0 & 0 & 1 
\end{pmatrix}.
\end{align}$  

다음 과정을 통해 행렬 성분을 구할 수 있다.
$\begin{align}
L_1^{-1} A = B, \quad
L_2^{-1} B = C, \quad
L_3^{-1} C = D
\end{align}$

In [12]:
import numpy as np
A=np.array([[1,3,-5,2],[0,4,-2,1],[2,-1,3,-1],[1,1,1,1]])
b=np.array([0,6,5,10])
x=np.linalg.solve(A,b) # much faster than inv
x

array([1., 2., 3., 4.])

## 회전
* z축을 중심으로 좌표축을 $x$만큼 회전하는 회전행렬은 다음과 같다.  
$\begin{align}
R(x)=
\begin{pmatrix}
\cos x & \sin x & 0 \\
-\sin x & \cos x & 0 \\
0 & 0 & 1 
\end{pmatrix}
\end{align}$


In [13]:
import numpy as np
def rot(x):
    theta=x*np.pi/180
    return np.array([[np.cos(theta),np.sin(theta),0],[-np.sin(theta),np.cos(theta),0],[0,0,1]])

In [15]:
x=[2,0,0]
np.dot(rot(45),x)

array([ 1.41421356, -1.41421356,  0.        ])

$R x = x'$

In [19]:
np.linalg.solve(rot(45),np.array([1.4142,-1.414,0])) 

array([1.99983940e+00, 1.41421356e-04, 0.00000000e+00])