# 리스트와 배열

## 리스트(list)와 성분(element)
* check! int, float, str

In [137]:
# 리스트는 대괄호 []를 쓰며 괄호 안에 개별 성분이 들어간다.
a = [1,2,3,4,5]

In [138]:
# 성분 연산 : "0"부터 시작한다는 것을 명심할 것
a[0], a[3]

(1, 4)

In [139]:
a[1:3], a[:] # 1번 뒤부터 3번까지 성분, 모든 성분

([2, 3], [1, 2, 3, 4, 5])

In [140]:
a[1], a[3], a[1]+r1[3]

(2, 4, 6)

In [141]:
# 리스트 연산
b=a # 복사
b

[1, 2, 3, 4, 5]

In [142]:
c=[1, 3.14, "hi"] # 다양한 종류의 성분
b+c

[1, 2, 3, 4, 5, 1, 3.14, 'hi']

In [143]:
c*3

[1, 3.14, 'hi', 1, 3.14, 'hi', 1, 3.14, 'hi']

## 리스트 수정

In [108]:
a=[1,2,3,4,5]
a[0]=-1
a

[-1, 2, 3, 4, 5]

In [109]:
a[0:1]=[0,1]
a

[0, 1, 2, 3, 4, 5]

In [110]:
a[0:1]=[]
a

[1, 2, 3, 4, 5]

In [111]:
a[0]=[] # 참고
a

[[], 2, 3, 4, 5]

In [117]:
a.append(6)
a

[1, 2, 3, 4, 5, 6]

In [127]:
b=[]
b.append(1)
b.append(2)

In [128]:
b

[1, 2]

In [129]:
a.pop(), a.pop(2)

(6, 3)

In [130]:
a

[1, 2, 4, 5]

## len(), sum() 

In [131]:
a=[1,2,3,4,5]
len(a), sum(a)

(5, 15)

## 배열(array)
* 다차원 배열을 다루기 쉽다. 벡터, 행렬 연산이 쉽다. 빠르다!
* 주의 : 배열의 모든 성분은 같은 형식(int, float, 문자)로 구성되어 있어야 한다.

In [132]:
import numpy as np

## 배열 만들기

In [161]:
a=np.zeros(4,float)
b=np.ones(3,int)
a, b

(array([0., 0., 0., 0.]), array([1, 1, 1]))

In [162]:
c=np.zeros([2,3],float) # (2x3) matrix
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [163]:
d=[1,2,3,4]
e=np.array(d,float)
d, e

([1, 2, 3, 4], array([1., 2., 3., 4.]))

In [167]:
e[1],e[1:3],e[:]

(2.0, array([2., 3.]), array([1., 2., 3., 4.]))

In [183]:
f=np.array([[1,2],[3,4]],int)
f[0,0],f[0,:],f[1,:]

(1, array([1, 2]), array([3, 4]))

## 배열 연산

$\begin{pmatrix} 1& 2& 3 \end{pmatrix} + \begin{pmatrix} 1& -1& 1 \end{pmatrix}$

In [158]:
a=np.array([1,2,3],int)
b=np.array([1,-1,1],int)
a+b, a-b, a*b, a/b

(array([2, 1, 4]),
 array([0, 3, 2]),
 array([ 1, -2,  3]),
 array([ 1., -2.,  3.]))

$\begin{pmatrix} 1& 3 \\ 2& 4 \end{pmatrix} \begin{pmatrix} 4& -2 \\ -3& 1 \end{pmatrix} + \begin{pmatrix} 1& 2 \\ 2& 1 \end{pmatrix}$

In [160]:
a=np.array([[1,3],[2,4]],int)
b=np.array([[4,-2],[-3,1]],int)
c=np.array([[1,2],[2,1]],int)
np.dot(a,b)+c

array([[-4,  3],
       [-2,  1]])

* check more functions in numpy! 

https://numpy.org/devdocs/user/quickstart.html