# 행렬(matrix)

## Array! Hooray!

In [31]:
import numpy as np
M0 = np.array([[1,0],[0,1]])
M1 = np.array([[1,2],[3,4]])

In [32]:
print(3*M1, M0+M1, M0*M1)

[[ 3  6]
 [ 9 12]] [[2 2]
 [3 5]] [[1 0]
 [0 4]]


In [33]:
np.dot(M1,M1)

array([[ 7, 10],
       [15, 22]])

In [34]:
np.transpose(M1), np.linalg.inv(M1), np.linalg.eig(M1), np.linalg.det(M1)

(array([[1, 3],
        [2, 4]]), array([[-2. ,  1. ],
        [ 1.5, -0.5]]), (array([-0.37228132,  5.37228132]),
  array([[-0.82456484, -0.41597356],
         [ 0.56576746, -0.90937671]])), -2.0000000000000004)