# Multilayer Perceptron

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# sigmoid function
def f(x):
    return 1/(1+np.exp(-x))
def df(x):
    return x*(1-x)

In [3]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])

In [4]:
np.random.seed(1)

In [5]:
inputs = 3
hiddens = 4
outputs = 1

In [6]:
w0 = 2*np.random.random((inputs,hiddens))-1
w1 = 2*np.random.random((hiddens,outputs))-1

In [13]:
w0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [8]:
## neural networks test
layer0 = X
net1 = np.dot(layer0, w0)
layer1 = f(net1) # activation function
layer1[:,-1] = 1.0 # bias

net2 = np.dot(layer1, w1)
layer2 = f(net2)

In [12]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [11]:
layer1 

array([[0.44856632, 0.51939863, 0.45968497, 1.        ],
       [0.28639589, 0.32350963, 0.31236398, 1.        ],
       [0.40795614, 0.62674606, 0.23841622, 1.        ],
       [0.25371248, 0.42628115, 0.14321233, 1.        ]])

In [10]:
net2

array([[0.03407121],
       [0.12104278],
       [0.34840428],
       [0.37796754]])

In [27]:
error = layer2 - y # 오차
error

array([[ 0.6316672 ],
       [-0.31144896],
       [-0.28745858],
       [ 0.75340654]])

In [31]:
delta = error*df(layer2) # delta
delta

array([[ 0.14696606],
       [-0.06678976],
       [-0.05887903],
       [ 0.13997173]])

### backpropagation

In [33]:
h_error = np.dot(delta,w1.T) # transpose!
h_delta = h_error*df(layer1)

In [35]:
eta=0.1
w1 = w1 - eta*np.dot(layer1.T, delta)
w0 = w0 - eta*np.dot(layer0.T, h_delta)