# Multilayer Perceptron

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [29]:
# sigmoid function
def f(x):
    return 1/(1+np.exp(-x))
def df(x):
    return x*(1-x)

In [3]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0],[1],[1],[0]])

In [5]:
np.random.seed(1)

In [6]:
inputs = 3
hiddens = 4
outputs = 1

In [10]:
w0 = 2*np.random.random((inputs,hiddens))-1
w1 = 2*np.random.random((hiddens,outputs))-1

In [11]:
w0,w1

(array([[ 0.7527783 ,  0.78921333, -0.82991158, -0.92189043],
        [-0.66033916,  0.75628501, -0.80330633, -0.15778475],
        [ 0.91577906,  0.06633057,  0.38375423, -0.36896874]]),
 array([[ 0.37300186],
        [ 0.66925134],
        [-0.96342345],
        [ 0.50028863]]))

In [22]:
## neural networks test
layer0 = X
net1 = np.dot(layer0, w0)
layer1 = f(net1) # activation function
layer1[:,-1] = 1.0 # bias

net2 = np.dot(layer1, w1)
layer2 = f(net2)

In [23]:
layer2

array([[0.6316672 ],
       [0.68855104],
       [0.71254142],
       [0.75340654]])

In [27]:
error = layer2 - y # 오차
error

array([[ 0.6316672 ],
       [-0.31144896],
       [-0.28745858],
       [ 0.75340654]])

In [31]:
delta = error*df(layer2) # delta
delta

array([[ 0.14696606],
       [-0.06678976],
       [-0.05887903],
       [ 0.13997173]])

### backpropagation

In [33]:
h_error = np.dot(delta,w1.T) # transpose!
h_delta = h_error*df(layer1)

In [35]:
eta=0.1
w1 = w1 - eta*np.dot(layer1.T, delta)
w0 = w0 - eta*np.dot(layer0.T, h_delta)